plugins {
    id 'com.android.library'
}

android {
    namespace 'com.drake.net'
    compileSdk rootProject.ext.compileSdk
    defaultConfig {
        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdk
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildFeatures {
        viewBinding true
        buildConfig true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    implementation libs.appcompat
//    implementation(platform(libs.okhttp.bom))
    implementation libs.androidx.documentfile
    implementation(libs.okhttp)
}
